# Файл с описанием правил для rustfmt

edition = "2018" # форматирование кода под стиль издания 2018
max_width = 120 # максимальная кол-во символов в строке, при превышении форматирует код так что-бы уложится в данное ограничение