# Файл с описанием правил для rustfmt

# Форматирование кода под стиль издания 2018
edition = "2018"
# Максимальная кол-во символов в строке, при превышении форматирует код так что-бы уложится в данное ограничение
max_width = 120